steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_DEPLOY_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_DEPLOY_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
images:
- '${_DEPLOY_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'